name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 6 * * MON"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          set-distribution-checksum: false
